### ISSUE TITLE
Create a Post

### ISSUE THREAD

**Issue by Snc1730** [NSS-Evening-E22/starlight-stalkers-rare#1]
Given a user selects the "New Post" link in the navbar and are directed to the new post form
When they fill out the form correctly and submit
Then the post should be added and approved
And they should be directed to that post's detail page

**Comment by jjBaltz** [comment]
**Dev Notes**
-  Server Side: Within the `program.cs` file, create an API call using `app.MapPost` with the endpoint `("/posts")` with the parameter of Post.
- Make sure it creates a new id so that it has a unique identifier to call on and display properly.
- Return all posts to certify it was added to the rest properly.
