### ISSUE TITLE
Create Model: Posts

### ISSUE THREAD

**Issue by Snc1730** [NSS-Evening-E22/starlight-stalkers-rare#21]
Create a model for posts including:
Id
UserId
CatagoryId
Title
PublicationDate
Content

**Comment by jjBaltz** [comment]
Dev Notes
- Create a model with a public class named Post
- Include the `int`s: `Id`, `UserId`, and `CategoryId`. The `string`s: `Title` and `Content`. Lastly, the `DateTime` of `PublicationDate`.
- Add a `Comments`, `PostTags`, and `Categories` List to link to the other models.
- Set all properties to public since it will have unrestricted user input.
